### ISSUE TITLE
Fetch Seating Information

### ISSUE THREAD

**Issue by nhatnghiho** [gt-scheduler/crawler-v2#5]
### Description
We need a way to fetch real-time seating information from Oscar. Given that this is real-time, GTS exposes an independent endpoint in [#gt-scheduler/backend](https://github.com/gt-scheduler/backend) repo, which is https://gt-scheduler.azurewebsites.net/proxy/class_section. You'll be modifying the function behind this endpoint, which is in `backend/src/controllers/classSection.ts`.

I haven't been able to find a working endpoint for this so you'll need to do the investigation yourself!

### Acceptance Criteria
- [ ] Seating information is fetched correctly

### Other Notes
https://registration.banner.gatech.edu/StudentRegistrationSsb/ssb/searchResults/getEnrollmentInfo - this endpoint is a potential lead, but it errors if we call it outside of the Oscar's context.

**Comment by jazeved0** [comment]
Just to give some historical context: the reason that the GT Scheduler app fetches seating information from OSCAR through the proxy is because it just wasn't viable to do this in the crawler. If I remember correctly, seating information requires loading a **separate page for every section**, and the old Banner system was so slow that doing this would push the runtime of the crawler too high (and also start seeing what we suspected were rate-limits).

Instead, the purpose of the proxy was to:
- make it so that the seating was only loaded when the user *really* wanted to load it. This results in a worse UX (wouldn't it be nicer to see the seating of all sections in a course to compare with?)
- bypass [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) security policies that the browser would enforce if the app tried to fetch the HTML of the page directly inside the user's browser.

For what it's worth, with the frequency that the crawler runs at (once every 30 minutes), it would probably be totally fine to have seating information that is max 30 minutes behind (but that's subjective, feel free to disagree).
